site_name: My Base Knowledge

# Repository
repo_name: gabrielbdornas/my-base-knowledge
repo_url: https://github.com/gabrielbdornas/my-base-knowledge
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  logo: assets/images/logo-no-background.png
  language: en
  custom_dir: docs/overrides
  features:
    # - announce.dismiss
    - content.code.annotate
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    - content.action.edit
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
    edit: material/pencil
    view: material/eye

markdown_extensions:
  - admonition
  - pymdownx.details
  - abbr
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - toc:
      permalink: ⚓︎
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - assets/style.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
extra_javascript:
  - assets/style.js
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js

extra: # Footer
  social:
    - icon: fontawesome/brands/youtube
      name: My YouTube Channel.
      link: https://www.youtube.com/channel/UCoMuk7Pk3VzUYQtuqa6fLTw
    - icon: fontawesome/solid/flag
      name: Material for MkDocs Icons, Emojis.
      link: https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime
      enable_creation_date: true
  - search:
      lang:
        - en
        - pt
  - blog:
      post_url_format: "{slug}"
      archive: false
      categories_toc: true
      post_excerpt: required
