# This uses a reusable workflow
name: Publish documentation

on:
  push:
    branches:
      - main

jobs:
  publish_documentation:
    runs-on: Ubuntu-20.04
    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2

      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install packages
        run: pip install -r requirements.txt

      - run: git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Publish Documentation
        run: mkdocs gh-deploy
